00000     0 output/randomNetwork.py.err
11718     1 output/randomNetwork.py.out
